test:
  service: Disk
  root: <%#= Rails.root.join("tmp/storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
  service: Disk
  root: <%#= Rails.root.join("tmp/storage") %>
