development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

staging:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: omg_rails_staging

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: omg_rails_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %> # https://github.com/chatwoot/chatwoot/issues/2420
